=begin
gotten from http://everything2.com/title/Books+that+will+induce+a+mindfuck

Parsed with nokogiri 'cause hpricot breaks with bad html.

Used this:
Nokogiri::HTML open "http://everything2.com/title/Books+that+will+induce+a+mindfuck"

elems = doc.css(".content > ul > li").collect {|group| name = group.css("a").first.inner_text; books = group.css("ul > li").collect{|book| book.inner_text}; {:author=>name, :books=>books} }

and then this:

elems.each { |group| group[:books].each {|book| f.write(%{Book.create(:author=>"#{group[:author]}", :title=>"#{book}")\n})}  }
=end

Book.create(:author=>"Adams, Douglas", :title=>"The Hitchhiker's Guide to the Galaxy")
Book.create(:author=>"Adams, Douglas", :title=>"The Restaurant at the End of the Universe")
Book.create(:author=>"Adams, Douglas", :title=>"Life, the Universe, and Everything")
Book.create(:author=>"Adams, Douglas", :title=>"So Long, and thanks for all the fish")
Book.create(:author=>"Adams, Douglas", :title=>"Mostly Harmless")
Book.create(:author=>"Adams, Douglas", :title=>"Dirk Gently's Holistic Detective Agency")
Book.create(:author=>"Richard Adams", :title=>"Watership Down")
Book.create(:author=>"Alighieri, Dante", :title=>"Inferno")
Book.create(:author=>"Allende, Isobel", :title=>"The House of the Spirits")
Book.create(:author=>"Asimov, Isaac", :title=>"Foundation")
Book.create(:author=>"Asimov, Isaac", :title=>"The Bicentennial Man")
Book.create(:author=>"Atwood, Margaret", :title=>"A Handmaid's Tale")
Book.create(:author=>"Atwood, Margaret", :title=>"The Edible Woman")
Book.create(:author=>"Atwood, Margaret", :title=>"Surfacing")
Book.create(:author=>"Ayliffe, John Stephen", :title=>"Blind Man's Bluff")
Book.create(:author=>"Banks, Iain", :title=>"The Bridge")
Book.create(:author=>"Banks, Iain", :title=>"The Wasp Factory")
Book.create(:author=>"Banks, Iain", :title=>"Use of Weapons")
Book.create(:author=>"Bantok, Nick", :title=>"Griffin and Sabine")
Book.create(:author=>"Barth, John", :title=>"Chimera")
Book.create(:author=>"Bear, Greg", :title=>"Blood Music")
Book.create(:author=>"Bester, Alfred", :title=>"Tiger! Tiger!")
Book.create(:author=>"Bey, Hakim", :title=>"Temporary Autonomous Zone")
Book.create(:author=>"Block, Francesca Lia", :title=>"Dangerous Angels - the Weetzie Bat books")
Book.create(:author=>"Boethius", :title=>"Consolation of Philosophy")
Book.create(:author=>"Borges, Jorge Luis", :title=>"Ficciones (Fictions)")
Book.create(:author=>"Borges, Jorge Luis", :title=>"The Cirular Ruins")
Book.create(:author=>"Bradbury, Ray", :title=>"Fahrenheit 451")
Book.create(:author=>"Bradbury, Ray", :title=>"Dandelion Wine")
Book.create(:author=>"Bryant, Dorothy", :title=>"The Kin Of Ata Are Waiting For You")
Book.create(:author=>"Bulgakov, Mikhail", :title=>"The Master and Margarita")
Book.create(:author=>"Bulgakov, Mikhail", :title=>"The Heart of a Dog")
Book.create(:author=>"Burgess, Anthony", :title=>"A Clockwork Orange")
Book.create(:author=>"Burroughs, William S.", :title=>"Junkie")
Book.create(:author=>"Burroughs, William S.", :title=>"Naked Lunch")
Book.create(:author=>"Burroughs, William S.", :title=>"The Ticket That Exploded")
Book.create(:author=>"Burroughs, William S.", :title=>"Junky's Christmas")
Book.create(:author=>"Camus, Albert", :title=>"The Outsider")
Book.create(:author=>"Camus, Albert", :title=>"The Myth of Sisyphus")
Book.create(:author=>"Camus, Albert", :title=>"The Stranger")
Book.create(:author=>"Camus, Albert", :title=>"The Plague")
Book.create(:author=>"Capote, Truman", :title=>"In Cold Blood")
Book.create(:author=>"Card, Orson Scott", :title=>"Ender's Game")
Book.create(:author=>"Card, Orson Scott", :title=>"Speaker for the Dead")
Book.create(:author=>"Card, Orson Scott", :title=>"Xenocide")
Book.create(:author=>"Card, Orson Scott", :title=>"Pastwatch: The Redemption of Christopher Columbus")
Book.create(:author=>"Card, Orson Scott", :title=>"Songmaster")
Book.create(:author=>"Carpenter, Edmund Snow", :title=>"They Became what They Beheld")
Book.create(:author=>"Carroll, Lewis", :title=>"Alice In Wonderland")
Book.create(:author=>"Carroll, Lewis", :title=>"Through the Looking-glass")
Book.create(:author=>"Carroll, Peter", :title=>"Liber Null")
Book.create(:author=>"Carroll, Peter", :title=>"Psychonaut")
Book.create(:author=>"Carroll, Peter", :title=>"Liber Kaos")
Book.create(:author=>"Castaneda, Carlos", :title=>"The teachings of Don Juan: a Yaqui way of knowledge")
Book.create(:author=>"Castaneda, Carlos", :title=>"A Separate Reality")
Book.create(:author=>"Castaneda, Carlos", :title=>"Journey to Ixtlan")
Book.create(:author=>"Cervantes, Miguel de", :title=>"Don Quixote")
Book.create(:author=>"Chase, Truddi", :title=>"When Rabbit Howls")
Book.create(:author=>"Chayefsky, Paddy", :title=>"Altered States")
Book.create(:author=>"Chuang Chou", :title=>"The Chuang-Tzu")
Book.create(:author=>"Clark, Arthur C.", :title=>"2001: A Space Oddysey")
Book.create(:author=>"Clark, Arthur C.", :title=>"Childhood's End")
Book.create(:author=>"Cortázar, Julio", :title=>"End of the Game and Other Stories")
Book.create(:author=>"Cortázar, Julio", :title=>"Rayuela (Hopscotch)")
Book.create(:author=>"Coupland, Douglas", :title=>"Microserfs")
Book.create(:author=>"Danielewski, Mark", :title=>"House of Leaves")
Book.create(:author=>"Dawkins, Richard", :title=>"The Selfish Gene")
Book.create(:author=>"Dick, Philip K.", :title=>"A Scanner Darkly")
Book.create(:author=>"Dick, Philip K.", :title=>"The Divine Invasion")
Book.create(:author=>"Dick, Philip K.", :title=>"VALIS")
Book.create(:author=>"Dickens, Charles", :title=>"A Tale of Two Cities")
Book.create(:author=>"Dostoevsky, Fyodor", :title=>"Crime and Punishment")
Book.create(:author=>"Dostoevsky, Fyodor", :title=>"Notes from the Underground")
Book.create(:author=>"Dostoevsky, Fyodor", :title=>"The Brothers Karamazov")
Book.create(:author=>"Eco, Umberto", :title=>"Foucalt's Pendulum")
Book.create(:author=>"Eco, Umberto", :title=>"The Name of the Rose")
Book.create(:author=>"Efsandiary, F.M.", :title=>"Upwingers")
Book.create(:author=>"Egan, Greg", :title=>"Diaspora")
Book.create(:author=>"Egan, Greg", :title=>"Distress")
Book.create(:author=>"Egan, Greg", :title=>"Permutation City")
Book.create(:author=>"Eliot, T.S.", :title=>"The Wasteland")
Book.create(:author=>"Ellis, Bret Easton", :title=>"American Psycho")
Book.create(:author=>"Ellis, Edward Robb", :title=>"A Nation in Torment")
Book.create(:author=>"Ende, Michael", :title=>"The Neverending Story")
Book.create(:author=>"Euclid", :title=>"The Elements")
Book.create(:author=>"Farmer, Philip Jose", :title=>"To Your Scattered Bodies Go")
Book.create(:author=>"Faulkner, William", :title=>"As I Lay Dying")
Book.create(:author=>"Feinberg, Leslie", :title=>"Stone Butch Blues")
Book.create(:author=>"Foucault, Michel", :title=>"Discipline and Punish")
Book.create(:author=>"Fowles, John", :title=>"The Magus")
Book.create(:author=>"Freud, Sigmund", :title=>"Civilization and Its Discontents")
Book.create(:author=>"Gaarder, Jostein", :title=>"Sophie's World")
Book.create(:author=>"Gardner, Laurence", :title=>"The Bloodline of the Holy Grail")
Book.create(:author=>"Gaiman, Neil", :title=>"Good Omens (with Terry Pratchett)")
Book.create(:author=>"Gaiman, Neil", :title=>"Neverwhere")
Book.create(:author=>"Gaiman, Neil", :title=>"American Gods")
Book.create(:author=>"Gilman, Charlotte Perkins", :title=>"Herland")
Book.create(:author=>"Gibson, William", :title=>"Burning Chrome")
Book.create(:author=>"Gibson, William", :title=>"Neuromancer")
Book.create(:author=>"Gibson, William", :title=>"Count Zero")
Book.create(:author=>"Gibson, William", :title=>"Mona Lisa")
Book.create(:author=>"Gibson, William", :title=>"Overdrive")
Book.create(:author=>"Gibson, William", :title=>"Virtual Light")
Book.create(:author=>"Gibson, William", :title=>"Idoru")
Book.create(:author=>"Gibson, William", :title=>"All Tomorrow's Parties")
Book.create(:author=>"Gleick, James", :title=>"Chaos : Making a New Science")
Book.create(:author=>"Gray, Alasdair", :title=>"Lanark")
Book.create(:author=>"Gogol, Nikolai", :title=>"The Diary of a Madman and Other Stories")
Book.create(:author=>"Golding, William", :title=>"Lord of the Flies")
Book.create(:author=>"Grimwood, Ken", :title=>"Replay")
Book.create(:author=>"Gurdjieff, G. I.", :title=>"Beelzebub's Tales to his Grandson")
Book.create(:author=>"Halperin, James L.", :title=>"The Truth Machine")
Book.create(:author=>"Hand, Elizabeth", :title=>"Waking the Moon")
Book.create(:author=>"Hand, Elizabeth", :title=>"Glimmering")
Book.create(:author=>"Hand, Elizabeth", :title=>"Winterlong")
Book.create(:author=>"Hand, Elizabeth", :title=>"Aestival Tide")
Book.create(:author=>"Hand, Elizabeth", :title=>"Icarus Descending")
Book.create(:author=>"Heinlein, Robert A.", :title=>"Stranger in a Strange Land")
Book.create(:author=>"Heinlein, Robert A.", :title=>"The Moon is a Harsh Mistress")
Book.create(:author=>"Heinlein, Robert A.", :title=>"Time Enough For Love")
Book.create(:author=>"Heller, Joseph", :title=>"Catch 22")
Book.create(:author=>"Herbert, Frank", :title=>"Dune")
Book.create(:author=>"Hermans, W.F.", :title=>"Het behouden huis")
Book.create(:author=>"Hermans, W.F.", :title=>"Nooit meer slapen")
Book.create(:author=>"Herr, Michael", :title=>"Dispatches")
Book.create(:author=>"Hesse, Herman", :title=>"Steppenwolf")
Book.create(:author=>"Hesse, Herman", :title=>"Siddhartha")
Book.create(:author=>"Hofstadter, Douglas", :title=>"Godel, Escher Bach: an Eternal Golden Braid")
Book.create(:author=>"Hofstadter, Douglas", :title=>"Metamagical Themas")
Book.create(:author=>"Hugo, Victor", :title=>"Les Miserables")
Book.create(:author=>"Huxley, Aldous", :title=>"Brave new World")
Book.create(:author=>"Huxley, Aldous", :title=>"The Doors of Perception")
Book.create(:author=>"Ibsen, Henrik", :title=>"A Doll's House")
Book.create(:author=>"Irving, John", :title=>"A Prayer for Owen Meany")
Book.create(:author=>"Jotce, Graham", :title=>"The Tooth Fairy")
Book.create(:author=>"Joyce, James", :title=>"Ulysses")
Book.create(:author=>"Joyce, James", :title=>"Finnegan's Wake")
Book.create(:author=>"Kafka, Franz", :title=>"The Penal Colony")
Book.create(:author=>"Kafka, Franz", :title=>"The Trial")
Book.create(:author=>"Kafka, Franz", :title=>"America")
Book.create(:author=>"Kafka, Franz", :title=>"The Castle")
Book.create(:author=>"Kafka, Franz", :title=>"Metamorphosis")
Book.create(:author=>"Kaku, Michio", :title=>"Hyperspace")
Book.create(:author=>"Kerouac, Jack", :title=>"On the Road")
Book.create(:author=>"Kerouac, Jack", :title=>"Visions of Cody")
Book.create(:author=>"Kerouac, Jack", :title=>"the Dharma Bums")
Book.create(:author=>"Kesey, Ken", :title=>"One Flew Over the Cuckoo's Nest")
Book.create(:author=>"Keyes, J. Gregory", :title=>"Empire of Unreason")
Book.create(:author=>"Keyes, J. Gregory", :title=>"Newton's Cannon")
Book.create(:author=>"Keyes, J. Gregory", :title=>"A Calculus of Angels")
Book.create(:author=>"Keyes, J. Gregory", :title=>"The Waterborne")
Book.create(:author=>"Keyes, J. Gregory", :title=>"The Blackgod")
Book.create(:author=>"Kidder, Tracy", :title=>"The Soul of a New Machine")
Book.create(:author=>"King, Stephen", :title=>"The Dark Tower series")
Book.create(:author=>"King, Stephen", :title=>"The Tommyknockers")
Book.create(:author=>"King, Stephen", :title=>"The Stand")
Book.create(:author=>"Kingston, Maxine Hong", :title=>"The Woman Warrior")
Book.create(:author=>"Knowles, John", :title=>"A Seperate Peace")
Book.create(:author=>"Land, Jon", :title=>"The Jared Kimberlain series")
Book.create(:author=>"Kosinski, Jerry", :title=>"The Painted Bird")
Book.create(:author=>"Lawrence, D. H.", :title=>"Lady Chatterly's Lover")
Book.create(:author=>"Leary, Timothy", :title=>"Politics of Ecstasy and Info-Psychology (aka Exo-Psychology)")
Book.create(:author=>"Lee, Tanith", :title=>"The Silver Metal Lover")
Book.create(:author=>"Lem, Stanislaw", :title=>"The Cyberiad")
Book.create(:author=>"Lem, Stanislaw", :title=>"Solaris")
Book.create(:author=>"Lem, Stanislaw", :title=>"The Futurological Congress")
Book.create(:author=>"Lem, Stanislaw", :title=>"Eden")
Book.create(:author=>"Lewis, C.S.", :title=>"That Hideous Strength")
Book.create(:author=>"Lewis, C.S.", :title=>"Out of the Silent Planet")
Book.create(:author=>"Lewis, C.S.", :title=>"Perelandra")
Book.create(:author=>"Leyner, Mark", :title=>"Et Tu, Babe")
Book.create(:author=>"Leyner, Mark", :title=>"The Tetherballs of Bouganville")
Book.create(:author=>"Lilly, John C.", :title=>"Programming and Metaprogramming in the Human Biocomputer")
Book.create(:author=>"Llewellyn, Grace", :title=>"The Teenage Liberation Handbook")
Book.create(:author=>"Longyear, Barry B.", :title=>"Sea of Glass")
Book.create(:author=>"Mailer, Norman", :title=>"Why Are We In Vietnam?")
Book.create(:author=>"Mandela, Nelson", :title=>"Long Walk to Freedom")
Book.create(:author=>"Marquez, Gabriel Garcia", :title=>"One Hundred Years of Solitude")
Book.create(:author=>"Mayle, Peter", :title=>"Where Did I Come From?")
Book.create(:author=>"McKenna, Terence", :title=>"The Archaic Revival")
Book.create(:author=>"McKenna, Terence", :title=>"The Invisible Landscape (with Dennis McKenna")
Book.create(:author=>"McKenna, Terence", :title=>"True Hallucinations")
Book.create(:author=>"Miller, Arthur", :title=>"A Canticle for Leibowitz")
Book.create(:author=>"Miller, Henry", :title=>"Plexus")
Book.create(:author=>"Milton, John", :title=>"Paradise Lost")
Book.create(:author=>"More, Thomas", :title=>"Utopia")
Book.create(:author=>"Morrison, Tony", :title=>"The Bluest Eye")
Book.create(:author=>"Murakami, Haruki", :title=>"A Wild Sheep Chase")
Book.create(:author=>"Murakami, Haruki", :title=>"The Wind-up Bird Chronicles")
Book.create(:author=>"Musashi, Miyamoto", :title=>"The Book of Five Rings")
Book.create(:author=>"Musil, Robert", :title=>"The Man Without Qualities (Der Mann ohne Eigenschaften)")
Book.create(:author=>"Nabokov, Vladimir", :title=>"Lolita")
Book.create(:author=>"Neville, Katherine", :title=>"The Eight")
Book.create(:author=>"Nietzsche, Friedrich", :title=>"The Gay Science")
Book.create(:author=>"Noon, Jeff", :title=>"Vurt")
Book.create(:author=>"Noon, Jeff", :title=>"Nymphomation")
Book.create(:author=>"Nørretranders, Tor", :title=>"The User Illusion")
Book.create(:author=>"Oates, Joyce Carol", :title=>"Blonde")
Book.create(:author=>"O'Brien, Flann", :title=>"The Third Policeman")
Book.create(:author=>"O'Brien, Timothy", :title=>"The Things They Carried")
Book.create(:author=>"Orwell, George", :title=>"1984")
Book.create(:author=>"Orwell, George", :title=>"Animal Farm")
Book.create(:author=>"Paglia, Camille", :title=>"Sexual Personae")
Book.create(:author=>"Palahniuk, Chuck", :title=>"Fight Club")
Book.create(:author=>"Palahniuk, Chuck", :title=>"Survivor")
Book.create(:author=>"Palahniuk, Chuck", :title=>"Choke")
Book.create(:author=>"Palahniuk, Chuck", :title=>"Invisible Monsters")
Book.create(:author=>"Perec, Georges", :title=>"A Void")
Book.create(:author=>"Plath, Sylvia", :title=>"The Bell Jar")
Book.create(:author=>"Pirsig, Robert", :title=>"Zen and the Art of Motorcycle Maintenance")
Book.create(:author=>"Pynchon, Thomas", :title=>"The Crying of Lot 49")
Book.create(:author=>"Pynchon, Thomas", :title=>"Gravity's Rainbow")
Book.create(:author=>"Quinn, Daniel", :title=>"Ishmael and The Story of B")
Book.create(:author=>"Rand, Ayn", :title=>"The Fountainhead")
Book.create(:author=>"Rhinehart, Luke", :title=>"The Dice Man")
Book.create(:author=>"Rhinehart, Luke", :title=>"Adventures of Wim")
Book.create(:author=>"Rhinehart, Luke", :title=>"Search for the Dice Man")
Book.create(:author=>"Rooney, Andy", :title=>"Not That You Asked")
Book.create(:author=>"Rosen, Robert", :title=>"Life Itself")
Book.create(:author=>"Ross, John", :title=>"Unintended Consequences")
Book.create(:author=>"Roy, Arundhati", :title=>"The Cost of Living")
Book.create(:author=>"Roy, Arundhati", :title=>"The God of Small Things")
Book.create(:author=>"Rucker, Rudy", :title=>"Software, Wetware, and Freeware")
Book.create(:author=>"Rushkoff, David", :title=>"The Ecstacy Club")
Book.create(:author=>"Sacks, Oliver", :title=>"Seeing Voices")
Book.create(:author=>"Sagan, Carl", :title=>"Pale Blue Dot")
Book.create(:author=>"Sagan, Carl", :title=>"The Demon-haunted World")
Book.create(:author=>"Saint-Exupéry, Antoine de", :title=>"The Little Prince")
Book.create(:author=>"Salinger, J. D.", :title=>"The Catcher in the Rye")
Book.create(:author=>"Saramago, Jose", :title=>"Blindness")
Book.create(:author=>"Sartre, Jean-Paul", :title=>"Nausea")
Book.create(:author=>"Shakespeare, William", :title=>"Hamlet")
Book.create(:author=>"Shelley, Mary", :title=>"Frankenstein")
Book.create(:author=>"Shem, Samuel", :title=>"The House of God")
Book.create(:author=>"Shem, Samuel", :title=>"Mount Misery")
Book.create(:author=>"Shepard, Lucius", :title=>"Life During Wartime")
Book.create(:author=>"Simmons, Dan", :title=>"HyperionThe Fall of Hyperion")
Book.create(:author=>"St. Augustine", :title=>"Confessions")
Book.create(:author=>"Stapledon, Olaf", :title=>"Starmaker")
Book.create(:author=>"Stein, Gertrude", :title=>"How to Write")
Book.create(:author=>"Stephenson, Neal", :title=>"Snow Crash")
Book.create(:author=>"Stephenson, Neal", :title=>"Cryptonomicon")
Book.create(:author=>"Stephenson, Neal", :title=>"Zodiac")
Book.create(:author=>"Stephenson, Neal", :title=>"Diamond Age")
Book.create(:author=>"Süskind, Patrick", :title=>"Das Parfum")
Book.create(:author=>"Tan, Amy", :title=>"The Joy Luck Club")
Book.create(:author=>"Thich Nhat Hanh", :title=>"Old Path, White Clouds")
Book.create(:author=>"Thompson, Hunter S.", :title=>"Fear and Loathing In Las Vegas")
Book.create(:author=>"Thurber, James", :title=>"The 13 Clocks")
Book.create(:author=>"Tolstoy, Leo", :title=>"The death of Ivan Ilyich")
Book.create(:author=>"Tolstoy, Leo", :title=>"the Kreuzer sonata")
Book.create(:author=>"Twain, Mark", :title=>"Letters from the Earth")
Book.create(:author=>"Twain, Mark", :title=>"The Mysterious Stranger")
Book.create(:author=>"Ullman, Ellen", :title=>"Close to the Machine")
Book.create(:author=>"The Bible", :title=>"The Bible")
Book.create(:author=>"Vian, Boris", :title=>"I Shall Spit On Your Grave")
Book.create(:author=>"Vinge, Vernor", :title=>"A Fire upon the Deep")
Book.create(:author=>"Vonnegut, Kurt", :title=>"Breakfast of Champions")
Book.create(:author=>"Vonnegut, Kurt", :title=>"Cat's Cradle")
Book.create(:author=>"Vonnegut, Kurt", :title=>"Player Piano")
Book.create(:author=>"Vonnegut, Kurt", :title=>"Sirens of Titan")
Book.create(:author=>"Vonnegut, Kurt", :title=>"Slaughter-house Five")
Book.create(:author=>"Wallace, David Foster", :title=>"Infinite Jest")
Book.create(:author=>"Irvine Welsh", :title=>"Filth")
Book.create(:author=>"Walsh, Lawrence E.", :title=>"Firewall")
Book.create(:author=>"Watts, Alan", :title=>"The Book")
Book.create(:author=>"Watts, Alan", :title=>"The Joyous Cosmology")
Book.create(:author=>"Watts, Alan", :title=>"The Wisdom of Insecurity")
Book.create(:author=>"Watts, Alan", :title=>"The Way Of Zen")
Book.create(:author=>"Wilbur, Ken", :title=>"Sex, Ecology, Spirituality")
Book.create(:author=>"Wilde, Oscar", :title=>"The Picture of Dorian Gray")
Book.create(:author=>"Wilder, Thornton", :title=>"The Bridge of San Lois Ray")
Book.create(:author=>"Wilson, Robert Anton", :title=>"The Illuminatus! Trilogy (with Robert Shea)")
Book.create(:author=>"Wilson, Robert Anton", :title=>"Prometheus Rising")
Book.create(:author=>"Wilson, Robert Anton", :title=>"Cosmic Trigger")
Book.create(:author=>"Wilson, Robert Anton", :title=>"Schrödinger's Cat Trilogy")
Book.create(:author=>"Wilson, Robert Anton", :title=>"The Universe Next Door")
Book.create(:author=>"Wilson, Robert Anton", :title=>"The Trick Top Hat")
Book.create(:author=>"Wilson, Robert Anton", :title=>"The Homing Pigeons")
Book.create(:author=>"Wolfe, Gene", :title=>"Peace")
Book.create(:author=>"Woolf, Virginia", :title=>"To the Lighthouse")
Book.create(:author=>"Yogananda, Paramahansa", :title=>"Autobiography Of A Yogi")
Book.create(:author=>"Yourcenar, Marguerite", :title=>"Anna... Soror")
Book.create(:author=>"Yourcenar, Marguerite", :title=>"Alexis")
Book.create(:author=>"Yourcenar, Marguerite", :title=>"Memoirs of Hadrian")
Book.create(:author=>"Yevgeny Zamyatin, Zamyatin, Yevgeny", :title=>"We")
Book.create(:author=>"Zinn, Howard", :title=>"A People's History of the United States")
Book.create(:author=>"Zukav, Gary", :title=>"Seat Of The Soul")
